(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "ac-js2")
(depends-on "adaptive-wrap")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "calfw")
(depends-on "cask")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "ecb")
(depends-on "enclose")
(depends-on "findr")
(depends-on "floobits")
(depends-on "git-commit-mode")
(depends-on "git-rebase-mode")
(depends-on "highlight")
(depends-on "idle-highlight")
(depends-on "inf-ruby")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "maxframe")
(depends-on "mew")
(depends-on "multi-term")
(depends-on "noctilux-theme")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "project-explorer")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "recentf-ext")
(depends-on "rubocop")
(depends-on "ruby-compilation")
(depends-on "ruby-tools")
(depends-on "s")
(depends-on "simple-httpd")
(depends-on "skewer-mode")
(depends-on "soft-morning-theme")
(depends-on "sr-speedbar")
(depends-on "tabbar")
(depends-on "w3m")
(depends-on "web-mode")
(depends-on "wrap-region")
